# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rosemary Orchard
email: contact@rosemaryorchard.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a blogger, podcaster and screencaster who loves automation and productivity. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Europe/London
show_excerpts: true
excerpt_separator: </p>
author: 
  name: Rosemary Orchard
  url: "https://rosemaryorchard.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-json-feed
  
pagination:
  enabled: true
  per_page: 10
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  indexpage: 'index'
  trail: 
    before: 2
    after: 2
    
feed:
  posts_limit: 1000