# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rosemary Orchard
email: contact@rosemaryorchard.com
description: >- 
  I am a blogger, podcaster and screencaster who loves automation and productivity.
timezone: Europe/London
show_excerpts: true
excerpt_separator: <!--more-->
permalink: /blog/:title/
author:
  name: "Rosemary Orchard"
  url: "https://rosemaryorchard.com"
  email: "contact@rosemaryorchard.com"
  photo: "assets/me.jpg"

collections:
  - recommendations

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - vendor/bin

# Build settings
theme: minima
minima:
  skin: auto
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-json-feed
  - jekyll-redirect-from

pagination:
  enabled: true
  permalink: "/page/:num/"
  per_page: 10
  title: ":title - page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  indexpage: "index"
  trail:
    before: 2
    after: 2

feed:
  posts_limit: 1000

jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - month
  layouts:
    year: archive-year
    month: archive-month
    category: archive-category
    tag: archive-tag
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
    tag: "/tag/:name/"
    category: "/category/:name/"
  slug_mode: latin

#Post/Page defaults
defaults:
  - scope:
      path: ""
    values:
      author: "Rosemary Orchard"
      exclude_rss: false
      title: ""
  - scope:
      path: "archive"
    values:
      sitemap: false
  - scope:
      path: "tag"
    values:
      sitemap: false
  - scope:
      path: "category"
    values:
      sitemap: false
  - scope:
      path: "posts"
    values:
      layout: "post"
      published: true
      sitemap: true
      hidden: false

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - vendor/bin
