name: Fetch Extra Data from Airtable

on:
  push:
    branches:
      - main
      - test-airtable

permissions:
  contents: write

jobs:
  extra-data:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2.2.3
        with:
          endpoint: ${{ secrets.AIRTABLE_RECOMMENDATIONS }}
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.AIRTABLE_TOKEN }}"} }'
          save-name: recommendations
          save-location: _data
      - name: Save the data
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: test-airtable # Pushes the updates to the main branch.
          folder: _data # The location of the file saved by the Fetch API Data action.
          target-folder: _data # Saves the data into '_data'