name: Fetch Extra Data from Airtable

on: []
  # push:
  #   branches:
  #     - main

permissions:
  contents: write

jobs:
  extra-data:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2.2.3
        with:
          endpoint: ${{ secrets.AIRTABLE_RECOMMENDATIONS }}
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.AIRTABLE_TOKEN }}"} }'
          save-name: recommendations.json
          save-location: _data
      - name: Save the data
        uses: test-room-7/action-update-file
        with:
          file-path: _data/recommendations.json
          commit-msg: Updated Recommmendations
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Save the data
      #   uses: JamesIves/github-pages-deploy-action@v4.4.1
      #   with:
      #     branch: test-airtable
      #     folder: fetch-api-data-action
      #     target-folder: _data # Saves the data into '_data'