name: Fetch Extra Data from Airtable

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  extra-data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2.2.3
        with:
          endpoint: ${{ secrets.AIRTABLE_RECOMMENDATIONS }}
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.AIRTABLE_TOKEN }}"} }'
#          target-folder: _data
#          save-location: _data
          save-name: recommendations
      - name: Save the data
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: main # Pushes the updates to the main branch.
          folder: fetch-api-data-action # The location of the file saved by the Fetch API Data action.
          target-folder: _data # Saves the data into '_data'