name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-pages:
    name: Build for GitHub Pages
    runs-on: ubuntu-latest
    steps:
      # Fetch recommendations from Airtable
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2.2.3
        with:
          endpoint: ${{ secrets.AIRTABLE_RECOMMENDATIONS }}
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.AIRTABLE_TOKEN }}"} }'
          save-location: _data
          save-name: recommendations
      # Check out the repo
      - uses: actions/checkout@v2
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Build the Jekyll site
      - uses: helaili/jekyll-action@v2
        with:
          jekyll_build_options: "JEKYLL_ENV=production -q  --config _config.yml,_config_prod.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
      - name: Telegram Action
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.BotToken }}
          chatId: ${{ secrets.ChatID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false