name: Automated Deployment to Server

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 120s
          script: |
            cd /home/git/JekyllBlog
            pwd
            git stash
            git pull -r
            /usr/local/rvm/gems/ruby-3.0.0/bin/bundle install
            JEKYLL_ENV=production /usr/local/rvm/gems/ruby-3.0.0/bin/bundle exec /usr/local/rvm/gems/ruby-3.0.0/bin/jekyll build --config _config.yml,_config_prod.yml
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        branding:
          icon: "message-square"
          color: "blue"
        with:
          to: ${{ secrets.ChatID }}
          token: ${{ secrets.BotToken }}
          disable_web_page_preview: true
      - name: Telegram Action
        uses: xinthink/action-telegram@v1.1
        branding:
          icon: "send"
          color: "blue"
        with:
          botToken: ${{ secrets.BotToken }}
          chatId: ${{ secrets.ChatID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
