name: Automated Deployment to Server

on:
  push:
    branches:
      - main
      
permissions: 
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  personal-server:
    runs-on: ubuntu-latest
    steps:
      # - name: Fetch Airtable Recommendations
      #   continue-on-error: true
      #   uses: JamesIves/fetch-api-data-action@v2.3.0
      #   with:
      #     endpoint: ${{ secrets.AIRTABLE_RECOMMENDATIONS }}
      #     configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.AIRTABLE_TOKEN }}"} }'
      #     save-name: recommendations
          # save-location: _data
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Recommendation File
      # - name: Save Airtable Recommendations
      #   uses: test-room-7/action-update-file@v1
      #   with:
      #     file-path: _data/recommendations.json
      #     commit-msg: Updated Recommmendations
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Save Recommendations
      #   continue-on-error: true
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: main # Pushes the updates to the main branch.
      #     folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
      #     target-folder: _data # Saves the data into the 'data' directory on the main branch.
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          JEKYLL_ENV: "production"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: JEKYLL_ENV,fetchApiData
          script: |
            cd ~/JekyllBlog;
            git stash;
            git pull -r;
            curl "${{ secrets.AIRTABLE_RECOMMENDATIONS }}" \
-H "Authorization: Bearer ${{ secrets.AIRTABLE_TOKEN }}" >> _data/recommendations.json
            $(which bundle) install;
            bundle exec jekyll build --config _config.yml,_config_prod.yml,_config_local.yml --quiet && echo 0;
      - name: Telegram Action
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.BotToken }}
          chatId: ${{ secrets.ChatID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false