name: Automated Deployment to Server

on:
  push:
    branches:
      - main
      
permissions: 
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  personal-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          JEKYLL_ENV: "production"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: JEKYLL_ENV,fetchApiData
          script: |
            cd ~/JekyllBlog;
            git stash;
            git pull -r;
            curl "${{ secrets.AIRTABLE_RECOMMENDATIONS }}" -H "Authorization: Bearer ${{ secrets.AIRTABLE_TOKEN }}" > _data/recommendations.json
            cat _data/recommendations.json | jq '.records | map(.fields)' > _data/recommendations.json
            $(which bundle) install;
            bundle exec jekyll build --config _config.yml,_config_prod.yml,_config_local.yml --quiet && echo 0;
      - name: Telegram Action
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.BotToken }}
          chatId: ${{ secrets.ChatID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false