name: Automated Deployment to Server

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  personal-server:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 120s
          script: |
            touch debug.txt
            echo 'eval "pwd: $(pwd)"' >> debug.txt
            echo 'eval "which ruby: $(which ruby)"' >> debug.txt
            echo 'eval "ruby -v: $(ruby -v)"' >> debug.txt
            echo 'eval "which bundle $(which bundle)"' >> debug.txt
            echo 'eval "bundle -v: $(bundle -v)"' >> debug.txt
            cd ~/JekyllBlog
            git stash
            git pull -r
            $(which bundle) install
            export JEKYLL_ENV=production
            bundle exec jekyll build --config _config.yml,_config_prod.yml,_config_local.yml
      - name: Telegram Action
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.BotToken }}
          chatId: ${{ secrets.ChatID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false