name: Automated Deployment to Server

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  personal-server:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        env:
          JEKYLL_ENV: "production"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: JEKYLL_ENV
          script: |
            cd ~/JekyllBlog;
            git stash;
            git pull -r;
            $(which bundle) install;
            bundle exec jekyll build --config _config.yml,_config_prod.yml,_config_local.yml && echo 0;
      - name: Telegram Action
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.BotToken }}
          chatId: ${{ secrets.ChatID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false